export const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  GOOGLE_SIGNIN_SUCCESS: "GOOGLE_SIGNIN_SUCCESS",
  GOOGLE_SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",
};